services:
  - type: web
    name: national-parks-chatbot-api
    env: python
    runtime: python
    buildCommand: pip install --upgrade pip setuptools wheel && pip install --no-cache-dir --extra-index-url https://download.pytorch.org/whl/cpu -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    region: oregon
    plan: free
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
    healthCheckPath: /health
